[package]
name = "PriceTracker"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.dev]
opt-level = 0
incremental = true

[lints.rust]
warnings = "allow"

[lints.clippy]
disallowed_types = "deny"

[dependencies]
tokio = { version = "1.51.1", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.13.2", features = ["json", "gzip", "deflate"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
once_cell = "1.21.4"
axum = "0.8.8"
scraper = "0.26.0"
futures = "0.3.32"
regex = "1.12.3"
csv = "1.4.0"
chrono = { version = "0.4.44", features = ["serde"] }
sqlx = { version = "0.9.0-alpha.1", features = ["runtime-tokio", "tls-native-tls", "postgres", "uuid", "json", "chrono", "macros"] }
dotenv = "0.15.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23",features = ["env-filter"] }
thiserror = "2.0.18"
async-trait = "0.1.89"
playwright-rs = "0.12.3"
strsim = "0.11.1"
humantime-serde = "1.1.1"
strum = "0.28.0"
strum_macros = "0.28.0"
tower-http = { version = "0.6.11", features = ["cors"] }
axum-extra = { version = "0.12.6", features = ["query"] }
openrouter-rs = "0.10.0"